# Generated by Django 5.0.3 on 2024-03-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('cv', models.FileField(upload_to='cvs/')),
                ('job_description', models.FileField(upload_to='job_descriptions/')),
            ],
        ),
    ]
